### ISSUE TITLE
Add xfce4-goodies

### ISSUE THREAD

**Issue by JCGoran** [schuellerf/xfce-test#13]
It would be nice if  the `xfce4-goodies` package (and their 4.14pre counterparts) could be added to the distribution, as I'm sure there are plenty of people using them along with the standard xfce programs, and manually installing some of them from source can be a bit complicated and time-consuming.

**Comment by schuellerf** [comment]
@JCGoran you can try the "latest" container. I didn't have time to test the container but it should contain the missing components.

**Comment by JCGoran** [comment]
@schuellerf could you possibly add the `xfce4-notes-plugin`? It seems to be the only one missing from the 'usual' ones (i.e. this [list](https://packages.debian.org/sid/xfce4-goodies) from Debian). Also, the `xfce4-whiskermenu-plugin` doesn't appear to follow the usual `autogen.sh` installation pattern, but uses `cmake` instead, so manual installation is necessary. Other than that, everything works perfectly!

**Comment by schuellerf** [comment]
@JCGoran I added `xfce4-notes-plugin` as it was missing, but I don't understand the problem with `xfce4-whiskermenu-plugin`. When you look at `container_scripts/build_all.sh` all are compiled the same...
Please tell me what "manual installation" steps you think are necessary and I'll check what the problem is - Thanks

**Comment by JCGoran** [comment]
For `xfce4-whiskermenu-plugin`, there is no `autogen.sh` file at all because it doesn't use GNU `autoconf`/`autotools`, but rather `cmake`, so the install instructions are basically:
1. `cd` to dir
2. `mkdir build && cd build`
3. `cmake ..`
4. `sudo make install`

Maybe you can modify https://github.com/schuellerf/xfce-test/blob/b8941918b28359e67b9b659a08ea31bc31f35f80/container_scripts/build_all.sh#L95
into something like
```bash
if [ $NAME == "xfce4-whiskermenu-plugin" ]; then
    mkdir build && cd build && cmake .. && sudo make install
else
    ./autogen.sh $AUTOGEN_OPTIONS 
fi
```
then I think it should work out of the box.

**Comment by schuellerf** [comment]
Thanks for this hint! Obviously I didn't check all packages (there are some more not compiling...)

**Comment by schuellerf** [comment]
This should be resolved, isn't it?
