### ISSUE TITLE
Cannot load the container with xephyr (xephir doesn't even start)

### ISSUE THREAD

**Issue by brunoais** [schuellerf/xfce-test#17]
```
me@myPC:/path/to/repos/xfce-test$ sudo -u dockerU ./xfce-test start
[sudo] password for me: 
You are working with the container: latest
No protocol specified

Xephyr cannot open host display. Is DISPLAY set?
xfce-test-1
```
I'm running ubuntu. I don't get what is wrong. Reading the `xfce-test` isn't helping either

**Comment by schuellerf** [comment]
This is not really related to Xephir. Your X11 setup is somehow wrong that the user "dockerU" can't access the DISPLAY of the user "me".
As a workaround you can try enabling all of your local users access to your display
xhost +LOCAL:
and then call your sudo … command again

**Comment by brunoais** [comment]
OK!.... That was the issue. Thank you.
