### ISSUE TITLE
Regular container updates

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#18]
Thanks for the great work having this docker container, but it would be great to have it regularly update each two weeks, as it hasn't been update in a month now.

**Comment by schuellerf** [comment]
As far as I know it's not a function of docker Hub to build regularly
But I triggered it now manually and I'll find a way 🤔

**Comment by philipzae** [comment]
Thanks, as i build the /git repos manually in the environment and then lose it all when i restart.

**Comment by philipzae** [comment]
I see multiple builds being built on docker over the last 2 days, so I presume the continuous building it working now.

**Comment by schuellerf** [comment]
Actually the builds in the last days were just changes and features, but I also managed to setup a weekly build: Fridays @10:00 (to be freshly available on the weekend)
If it works tomorrow I'll maybe mention in the readme 🤔

**Comment by schuellerf** [comment]
> Thanks, as i build the /git repos manually in the environment and then lose it all when i restart.

You can keep the docker image if you want to retain your Changes - that's not the main usecase of this project but a basic docker function. Do you need help with that?

**Comment by philipzae** [comment]
Thanks for working on the weekly builds. If they happen every friday then I wouldn't need to build the git repos manually.

> You can keep the docker image if you want to retain your Changes - that's not the main usecase of this project but a basic docker function. Do you need help with that?
Yes your guidance on this would be great, as I have no knowledge of docker.

I've written this guide on the xfce wiki to make it easy for new comers to get xfce-test up and running.
https://wiki.xfce.org/testing/xfce-test
