### ISSUE TITLE
Xephyr blank screen

### ISSUE THREAD

**Issue by fatalhalt** [schuellerf/xfce-test#2]
Hello,

I would like to try out the docker image, this is pretty awesome that we can test xfce this way. I ran into an issue where my Xephyr doesn't display anything, any ideas?

```
[root@ROG /home/kyle]# docker run --name xfce-test --rm --env DISPLAY=":1" --volume /tmp/.X11-unix:/tmp/.X11-unix schuellerf/xfce-test:ubuntu_17.04
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
gpg-agent[16]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent[16]: directory '/home/test_user/.gnupg' created
gpg-agent[16]: directory '/home/test_user/.gnupg/private-keys-v1.d' created
gpg-agent[17]: gpg-agent (GnuPG) 2.1.15 started

(xfce4-session:1): xfce4-session-WARNING **: gpg-agent returned no PID in the variables

(xfce4-session:1): xfce4-session-WARNING **: xfsm_manager_load_session: Something wrong with /home/test_user/.cache/sessions/xfce4-session-10600b929708:1, Does it exist? Permissions issue?
env: 'Thunar': No such file or directory

(xfsettingsd:33): xfsettingsd-WARNING **: Property "/Gdk/WindowScalingFactor" has an unsupported type "guint".

(xfsettingsd:33): libupower-glib-WARNING **: Couldn't connect to proxy: Could not connect: No such file or directory

(xfsettingsd:33): libupower-glib-CRITICAL **: up_client_get_lid_is_closed: assertion 'UP_IS_CLIENT (client)' failed

(xfsettingsd:33): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(xfsettingsd:33): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xfwm4:19): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed

(xfsettingsd:33): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed

(xfsettingsd:33): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(xfsettingsd:33): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(xfwm4:19): xfwm4-WARNING **: The property '/general/double_click_distance' of type int is not supported

(xfwm4:19): xfwm4-WARNING **: GLX extension missing, GLX support disabled.

(xfdesktop:27): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(xfce4-session:1): xfce4-session-WARNING **: failed to run script: Failed to execute child process ?/usr/bin/pm-is-supported? (No such file or directory)

(xfce4-session:1): xfce4-session-WARNING **: failed to run script: Failed to execute child process ?/usr/bin/pm-is-supported? (No such file or directory)

(xfwm4:19): xfwm4-WARNING **: Another compositing manager is running on screen 0

(xfce4-panel:23): Gtk-WARNING **: Allocating size to panel-tasklist-arrow 0x55991472a5b0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(wrapper-2.0:56): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 28

(wrapper-2.0:56): Gtk-WARNING **: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node border, owner GtkFrame)

(wrapper-2.0:58): Gtk-WARNING **: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner XfceArrowButton)
```

I see some defunct processes within the container:
docker exec -i -t 10600b929708 /bin/bash
...
test_user@10600b929708:~$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
test_us+     1     0  0 01:34 ?        00:00:00 xfce4-session
test_us+     8     1  0 01:34 ?        00:00:00 /usr/bin/dbus-launch --sh-syntax --exit-with-session xfce4-session
test_us+     9     1  0 01:34 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
test_us+    11     1  0 01:34 ?        00:00:00 /usr/lib/x86_64-linux-gnu/xfce4/xfconf/xfconfd
test_us+    15     1  0 01:34 ?        00:00:00 /usr/bin/ssh-agent -s
test_us+    17     1  0 01:34 ?        00:00:00 /usr/bin/gpg-agent --sh --daemon --write-env-file /home/test_user/.cache/gpg-agent-info
test_us+    19     1  0 01:34 ?        00:00:00 xfwm4
test_us+    21     1  0 01:34 ?        00:00:00 [xfsettingsd] <defunct>
test_us+    23     1  0 01:34 ?        00:00:00 xfce4-panel
test_us+    25     1  0 01:34 ?        00:00:00 [env] <defunct>
test_us+    27     1  0 01:34 ?        00:00:00 xfdesktop
test_us+    30     1  0 01:34 ?        00:00:00 xscreensaver -no-splash
test_us+    33     1  0 01:34 ?        00:00:00 xfsettingsd
test_us+    35     1  0 01:34 ?        00:00:00 /usr/lib/at-spi2-core/at-spi-bus-launcher
test_us+    36     1  0 01:34 ?        00:00:00 [xfsettingsd] <defunct>
test_us+    41    35  0 01:34 ?        00:00:00 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3
test_us+    43     1  0 01:34 ?        00:00:00 /usr/lib/at-spi2-core/at-spi2-registryd --use-gnome-session
test_us+    48     1  0 01:34 ?        00:00:00 /usr/lib/x86_64-linux-gnu/tumbler-1/tumblerd
test_us+    56    23  0 01:34 ?        00:00:00 /usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-2.0 /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libsystray.so 6 167
test_us+    58    23  0 01:34 ?        00:00:00 /usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-2.0 /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libactions.so 2 167
test_us+    61     0  0 01:35 ?        00:00:00 /bin/bash
test_us+    94    61  0 01:36 ?        00:00:00 ps -ef
...

I'm trying this out on Ubuntu 16.10, X1 socket is there so that's good
[root@ROG /home/kyle]# ls -al /tmp/.X11-unix/X1 
srwxrwxrwx 1 root root 0 Apr 10 20:33 /tmp/.X11-unix/X1

Thank you.

**Comment by schuellerf** [comment]
Hi!
Great to hear that you try to work with xfce-test. The last time the black-screen problem went away we switched to a different version of xfwm4 (https://github.com/schuellerf/xfce-test/commit/3043cbbcbc04f1183d4a6092cccf60aecfc2fb44) did you also try master?

(Which is also the "latest" docker image "schuellerf/xfce-test:latest")

**Comment by fatalhalt** [comment]
Ahh yes that was it, thanks a bunch, I'm still new to docker. I was spawning +3 week old xfce container.
