### ISSUE TITLE
Enable sound settings

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#22]
Please compile with --enable-sound-settings.
https://gitlab.xfce.org/xfce/xfce4-settings/-/issues/205

**Comment by schuellerf** [comment]
fixed with https://github.com/schuellerf/xfce-test/commit/b1f5ebbcb4f1161d39ea86059cd66e3947d4e8f3 please check once the containers are built

**Comment by philipzae** [comment]
thanks
