### ISSUE TITLE
Add Elementary-xfce icon theme

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#25]
Please add the theme - https://github.com/shimmerproject/elementary-xfce

**Comment by ochosi** [comment]
You can easily install the theme in the container, or do you refer to including git master? If so, that's a little extra work because all source icons in the repo are SVG and in packaging we convert to png

**Comment by philipzae** [comment]
I think having it from git master would be best, so that any bugs that appear in the theme don't get reported for things that are already fixed, as that has happened to me a few times going off what is available in the xubuntu repo.

**Comment by philipzae** [comment]
Its in, though I couldn't see a difference between the four icon themes. @ochosi: where should I be able to see the difference?
