### ISSUE TITLE
Thunar not set to FileManager

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#27]
When I click on the folders on the desktop or the file manager icon in the bottom panel, it doesn't open thunar though Thunar is set in the Preferred Applications app as the file manager in 18.04 and does open it in 20.04 as its not built.

This was tested in the 20.04 and 18.04 builds from yesterday.

20.04
![image](https://user-images.githubusercontent.com/4412114/88243308-1148b500-cca1-11ea-8ea1-c7b126580a95.png)

18.04
![image](https://user-images.githubusercontent.com/4412114/88243137-794acb80-cca0-11ea-9361-f447f5ee4fc9.png)

**Comment by philipzae** [comment]
**20.04**
![image](https://user-images.githubusercontent.com/4412114/88273612-8214bf00-cceb-11ea-8453-2097eab28fed.png)

**Comment by schuellerf** [comment]
this seems to be obsolete - as soon as the upstream packages build again (see related issue) this will also work again
