### ISSUE TITLE
Many components not building

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#28]
This is from the 20.04 container from 
![image](https://user-images.githubusercontent.com/4412114/88273897-f2234500-cceb-11ea-8eaf-a51d6666e9d3.png)

This includes issue #27

**Comment by marcosins** [comment]
I built the components with `LOG=build.log PARALLEL_BUILDS=8 ./xfce-test build`,

I'm also attaching mi [`build.log`](https://github.com/schuellerf/xfce-test/files/4973419/build.log.zip) file in case it's useful.

```
*NOT OK: thunar-volman: xfce-4.14.0-32-gf70cf97
NOT OK: xfce4-appfinder: xfce4-appfinder-4.15.0-45-ga1d9ede
*NOT OK: xfce4-power-manager: xfce4-power-manager-1.7.0-107-gbd10e5f5
*NOT OK: xfce4-vala: xfce4-vala-4.10.0-5-g86ad5a7
NOT OK: thunar: thunar-4.15.1-48-gab192fac
*NOT OK: xfce4-notifyd: xfce4-notifyd-0.6.1-39-gb1ec634
*NOT OK: xfce4-screensaver: xfce4-screensaver-0.1.10-44-g35b9451
*NOT OK: xfce4-mixer: xfce4-mixer-4.11.0-237-g792e279
*NOT OK: ristretto: ristretto-0.10.0-115-gf883ab5
*NOT OK: parole: parole-1.0.5-46-g8e36fa7
*NOT OK: xfmpc: 0.3.0-27-g76b84db
*NOT OK: xfce4-notes-plugin: 1.8.1-197-gbf0935b
NOT OK: xfce4-netload-plugin cloning failed: 
*NOT OK: xfce4-mailwatch-plugin: xfce4-mailwatch-plugin-1.2.0-341-g6b808c7
*NOT OK: catfish: catfish-1.4.13-67-g465d400
*NOT OK: xfce4-xkb-plugin: 0.8.1-144-g6026349
*NOT OK: thunar-archive-plugin: thunar-archive-plugin-0.4.0-104-gb073ed0
*NOT OK: thunar-media-tags-plugin: thunar-media-tags-plugin-0.3.0-113-g6f5c3d7
```
`*`Same failed build as @philipzae

**Comment by schuellerf** [comment]
I added some missing dependencies with https://github.com/schuellerf/xfce-test/commit/9f94639611dc2d396bd8a61b7f6a08dd8312a1e2 
on ubuntu/20.04 branch for now. Other problems might be related to 
https://gitlab.xfce.org/xfce/libxfce4util/-/merge_requests/2
not being fixed in all components like
https://gitlab.xfce.org/xfce/xfce4-session/-/merge_requests/4
so those are not related to xfce-test I think

**Comment by philipzae** [comment]
Thanks for the update. Look forward to testing out the next build when it comes out.

**Comment by philipzae** [comment]
I pulled in the latest container and things still didn't build :cry: 
![image](https://user-images.githubusercontent.com/4412114/89111713-20cab980-d46a-11ea-8b5b-a8c2d641389c.png)

**Comment by philipzae** [comment]
I tried latest today (which was built on Dec 25th) and 29 components didn't build.

**Comment by schuellerf** [comment]
I'll try to get some time to check where the problems are...
Thanks for the hint

**Comment by philipzae** [comment]
Thanks. I'm currently using the ubuntu_20.04 build (14 components fail) and xfce-4.16pre2 build (4 components failed), though both are 4 weeks old.

**Comment by philipzae** [comment]
Tried latest today and it works fine, though a few still aren't building. You can cancel building xfce4-notes-plugin as it is [no longer supported](https://git.launchpad.net/~xubuntu-dev/ubuntu-seeds/+git/xubuntu/commit/?id=7b8107d1d4835eda966db432f228061601fa1540).

![image](https://user-images.githubusercontent.com/4412114/104109214-206dfe80-52e5-11eb-88d8-aec86d7f1816.png)

**Comment by philipzae** [comment]
All are building fine with xfce-test:devel container: 951cea790d0f1f7a257f2f38896532a8f7035500d72f660660ae3850dc5e4803
