### ISSUE TITLE
Unable to open text file in 18.04 container

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#29]
I presume mousepad is being built for the 18.04 container, but its not listed in the menu and I cant run it from the terminal. Text files are set to be open with Vim, but it gives an xterm error. I went into preferred applications and change the default terminal emulator to xfce terminal but that didn't fix it.

![image](https://user-images.githubusercontent.com/4412114/88274869-7de9a100-cced-11ea-8c7c-755dc0a1c10f.png)

**Comment by JCGoran** [comment]
Seems like mousepad actually fails to build on 18.04 due to missing dependencies; to build it, you can install the package `libgtksourceview-3.0-dev` with apt, and then recompile mousepad by running `./autogen.sh && sudo make install` in the `/git/mousepad` directory.

**Comment by schuellerf** [comment]
This should be already resolved, please check.
for some reason mousepad crashes the first time and subsequent starts work fine - I'm not sure if this is related to the container setup of xfce-test directly

**Comment by philipzae** [comment]
mousepad working fine now. Only 4 items that aren't compiling correctly in 18.04: thunar-volman, xfce4-vala, xfce4-mixer and xfce4-screenshooter.

**Comment by schuellerf** [comment]
So I'll close this issue then and check the other components in another context...
