### ISSUE TITLE
Preset text files to open in mousepad

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#32]
Would be great if text files were preconfigured to open in mousepad, so that clicking version_info.txt file on the desktop opens straight away.

**Comment by schuellerf** [comment]
please check if it works for you

**Comment by philipzae** [comment]
not sure how i could test it working if its not in the build, but after associating a text file with mousepad, mimeapps.list looked like this.

![image](https://user-images.githubusercontent.com/4412114/105223002-a9eabf80-5b74-11eb-911a-24879484cd79.png)

**Comment by schuellerf** [comment]
It will be part of the next containter https://github.com/schuellerf/xfce-test/blob/c9f5cdad5ddee69e7ad739dcc00ccfa1ac8d0d47/dockerfiles/Dockerfile-devel#L91
but I just checked, docker hub just did not build it yet (queued somehow).
I can also comment here once the build is done

**Comment by schuellerf** [comment]
Now it was built - please check

**Comment by philipzae** [comment]
It works.
