### ISSUE TITLE
Is it running the latest git

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#33]
I updated to the latest build from 3 days ago, but a number of patches that I wanted to test which are 2 weeks old, don't seem to be added.

examples
https://gitlab.xfce.org/xfce/thunar/-/commit/b6cfc27a828fd9fe826f5428cc93cfc8e980429b
https://gitlab.xfce.org/panel-plugins/xfce4-genmon-plugin/-/commit/d69c337e9f9e9cd6890d46832b031e7035a5187f

**Comment by schuellerf** [comment]
Did you use the devel container (devel Tag)?
https://github.com/schuellerf/xfce-test#devel
"lastest" tries to build the last git-tag (or release of each component)
which I think should be more stable (but currently is a little broken due to missing upstream git-tags)

**Comment by philipzae** [comment]
Sorry my bad. I presumed latest was git master. :D
