### ISSUE TITLE
Catfish doesn't work

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#34]
Tried running catfish in devel, latest and ubuntu 20.04 containers but all gave the same error.
![image](https://user-images.githubusercontent.com/4412114/104929816-d14b5c00-59bd-11eb-8b98-a75e3951558d.png)

**Comment by bluesabre** [comment]
Catfish requires python3-dbus. Most likely, this package is missing from the container.

https://packages.ubuntu.com/hirsute/catfish

**Comment by philipzae** [comment]
Seems its been needed since 20.04. https://packages.ubuntu.com/focal/catfish

**Comment by schuellerf** [comment]
Thanks for the hints, I also added python3-pexpect as this also seems to be needed during run-time.
Please check once the containers have been rebuilt (usually ~1-2hours)

**Comment by philipzae** [comment]
Its working now in devel. Thank you. Hope the fix also arrives in the other containers.
