### ISSUE TITLE
No new builds in 2+ weeks

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#37]
![image](https://user-images.githubusercontent.com/4412114/107996025-d28d9a00-6ff8-11eb-9632-340112b86d6f.png)

**Comment by schuellerf** [comment]
Docker hub changed their behavior - the image-build was triggered (weekly on Fridays) but did not refresh the sources (as my Dockerfile stayed the same)
I triggered the build now without build caching...
