### ISSUE TITLE
Is latest following the latest tags

### ISSUE THREAD

**Issue by philipzae** [schuellerf/xfce-test#38]
I tried latest from 6 days ago, but xfce4-panel is still version 4.16.0 rather than 4.16.1, whiskermenu is 2.5.0 rather than 2.5.3, and I presume there are others

**Comment by schuellerf** [comment]
Same here. This is kind of "on purpose" and I'm not aware of any solution that can be automated...
The "latest" container is building what I call "last_tag"
https://github.com/schuellerf/xfce-test/blob/master/container_scripts/build_all-latest.sh#L3
which actually searches the last tag to be found on **master**
https://github.com/schuellerf/xfce-test/blob/master/container_scripts/build_all.sh#L135

the tags you are referring to (e.g. xfce4-panel-4.16.1) are on the branch xfce-4.16
So this behavior is intended and described in the README.md like this: "…which ends up with the current master but going back to the last valid tag set…"

But you can use the container to also build different versions like other tags from other branches.
