### ISSUE TITLE
Build from git master

### ISSUE THREAD

**Issue by Skunnyk** [schuellerf/xfce-test#4]
Just to let you know that I have a basic setup with a build from git master of all components: https://github.com/Skunnyk/xfce-test
It's not finished yet (for example I need to add a default panel config to avoid the dialog popup on first runtime).
I didn't run the behave test with it :)
But at least we know that the build order is ok and there is no dependency loop with a build from scratch.

Maybe this can be a branch of xfce-test ?

**Comment by schuellerf** [comment]
nope - this doesn't look like a branch of xfce-test.
It rather looks like the new master :)

please just create a merge request.
All my initial tests pass with this anyway (just travis doesn't work stable)

**Comment by schuellerf** [comment]
... never mind - I just merged it :+1:

**Comment by Skunnyk** [comment]
Cool, thank you !
Panel master is broken for now, https://bugzilla.xfce.org/show_bug.cgi?id=13589 need to applied.
