### ISSUE TITLE
Default root password

### ISSUE THREAD

**Issue by DanielPower** [schuellerf/xfce-test#6]
The root password is not provided, and sudo is not included on the docker image. How can I obtain root access on this docker image so I can install additional xfce plugins for testing?

**Comment by schuellerf** [comment]
There is no password and you don't need any...
You can either change the Dockerfile to include your plugin (and run "make build") or just start your container and "dive in" as root (in a second terminal)
docker exec --tty --interactive --user 0:0 xfce-test /bin/bash
and run your favorite command :)

**Comment by DanielPower** [comment]
Thank you. This is my first time using Docker, so I was unaware.
